lgb:
  objective: regression
  random_seed: 1234
  learning_rate: 0.05
  n_estimators: 1000
  num_leaves: 33
  max_bin: 125
  bagging_fraction: 0.7197362581993618
  bagging_freq': 4
  feature_fraction': 0.4684501358427995
  min_data_in_leaf': 14
  min_sum_hessian_in_leaf: 2

xgb:
  learning_rate: 0.05
  seed: 1234
  max_depth: 6
  colsample_bytree: 0.330432640328732
  sub_sample: 0.7158427239902707

xgbr:
  learning_rate: 0.05
  seed: 1234
  max_depth: 6
  colsample_bytree: 0.330432640328732
  subsample: 0.7158427239902707

mlpr:
  random_state: 1234
  learning_rate_init: 0.1
  learning_rate: 'adaptive'
  hidden_layer_sizes: [100,100,100]
  batch_size: 101
  max_iter: 500